export interface Isettings {
    ÁLTALÁNOS: boolean,
    BIOLÓGIA: boolean,
    ÉPÍTÉSZET: boolean,
    FILM: boolean,
    FÖLDRAJZ: boolean,
    IRODALOM: boolean,
    JÁTÉK: boolean,
    KONYHA: boolean,
    KÉPZŐMŰVÉSZET: boolean,
    MAGYARORSZÁG: boolean,
    MŰVÉSZET: boolean,
    NYELV: boolean,
    OPERA: boolean,
    ORSZÁGOK: boolean,
    SPORT: boolean,
    SZÍNHÁZ: boolean,
    TECHNIKA: boolean,
    TUDOMÁNY: boolean,
    TÖRTÉNELEM: boolean,
    VALLÁS: boolean,
    ZENE: boolean
}